//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSP_Claim_Search.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claims_Headers
    {
        public string SEQ_CLAIM_ID { get; set; }
        public string SUBSCRIBER_ID { get; set; }
        public string CLAIM_NUMBER { get; set; }
        public string CATEGORY_OF_SVC { get; set; }
        public string PAT_CONTROL_NO { get; set; }
        public string ICD_PRIM_DIAG { get; set; }
        public Nullable<System.DateTime> PRIMARY_SVC_DATE { get; set; }
        public Nullable<System.DateTime> SVC_TO_DATE { get; set; }
        public Nullable<System.DateTime> CLAIM_THRU_DATE { get; set; }
        public Nullable<System.DateTime> POST_DATE { get; set; }
        public Nullable<System.DateTime> CHECK_DATE { get; set; }
        public string CHECK_NUMBER { get; set; }
        public Nullable<System.DateTime> DATE_RECEIVED { get; set; }
        public Nullable<System.DateTime> ADJUD_DATE { get; set; }
        public string CMS_CertificationNumber { get; set; }
        public string SVC_PROV_ID { get; set; }
        public string SVC_PROV_FULL_NAME { get; set; }
        public string SVC_PROV_NPI { get; set; }
        public string PROV_SPEC { get; set; }
        public string PROV_TYPE { get; set; }
        public string PROVIDER_PAR_STAT { get; set; }
        public string ATT_PROV_ID { get; set; }
        public string ATT_PROV_FULL_NAME { get; set; }
        public string ATT_PROV_NPI { get; set; }
        public string REF_PROV_ID { get; set; }
        public string REF_PROV_FULL_NAME { get; set; }
        public string VENDOR_ID { get; set; }
        public string VEND_FULL_NAME { get; set; }
        public string IRS_TAX_ID { get; set; }
        public string DRG_CODE { get; set; }
        public string BILL_TYPE { get; set; }
        public Nullable<System.DateTime> ADMISSION_DATE { get; set; }
        public string AUTH_NUMBER { get; set; }
        public string ADMIT_SOURCE_CODE { get; set; }
        public string ADMIT_HOUR { get; set; }
        public string DISCHARGE_HOUR { get; set; }
        public string PATIENT_STATUS { get; set; }
        public string CLAIM_STATUS { get; set; }
        public string PROCESSING_STATUS { get; set; }
        public string CLAIM_TYPE { get; set; }
        public Nullable<decimal> TOTAL_BILLED_AMT { get; set; }
        public Nullable<decimal> TOTAL_PAID_AMT { get; set; }
        public string SrcAdiTableName { get; set; }
        public int SrcAdiKey { get; set; }
        public System.DateTime LoadDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<decimal> CalcdTotalBilledAmount { get; set; }
        public Nullable<int> BENE_PTNT_STUS_CD { get; set; }
        public Nullable<int> DISCHARGE_DISPO { get; set; }
    }
}
