//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSP_Claim_Search.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ACDW_CLMS_SHCN_MSSPEntities1 : DbContext
    {
        public ACDW_CLMS_SHCN_MSSPEntities1()
            : base("name=ACDW_CLMS_SHCN_MSSPEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Claims_Details> Claims_Details { get; set; }
        public virtual DbSet<Claims_Diags> Claims_Diags { get; set; }
        public virtual DbSet<Claims_Headers> Claims_Headers { get; set; }
    
        public virtual ObjectResult<sp_Get_ClaimDetails_Result> sp_Get_ClaimDetails(string clientMemberKey, string seqClaimID)
        {
            var clientMemberKeyParameter = clientMemberKey != null ?
                new ObjectParameter("ClientMemberKey", clientMemberKey) :
                new ObjectParameter("ClientMemberKey", typeof(string));
    
            var seqClaimIDParameter = seqClaimID != null ?
                new ObjectParameter("SeqClaimID", seqClaimID) :
                new ObjectParameter("SeqClaimID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Get_ClaimDetails_Result>("sp_Get_ClaimDetails", clientMemberKeyParameter, seqClaimIDParameter);
        }
    
        public virtual ObjectResult<sp_Get_ClaimDiags_Result> sp_Get_ClaimDiags(string clientMemberKey, string seqClaimID)
        {
            var clientMemberKeyParameter = clientMemberKey != null ?
                new ObjectParameter("ClientMemberKey", clientMemberKey) :
                new ObjectParameter("ClientMemberKey", typeof(string));
    
            var seqClaimIDParameter = seqClaimID != null ?
                new ObjectParameter("SeqClaimID", seqClaimID) :
                new ObjectParameter("SeqClaimID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Get_ClaimDiags_Result>("sp_Get_ClaimDiags", clientMemberKeyParameter, seqClaimIDParameter);
        }
    
        public virtual ObjectResult<sp_Get_ClaimHeader_Result> sp_Get_ClaimHeader(string clientMemberKey, string seqClaimID)
        {
            var clientMemberKeyParameter = clientMemberKey != null ?
                new ObjectParameter("ClientMemberKey", clientMemberKey) :
                new ObjectParameter("ClientMemberKey", typeof(string));
    
            var seqClaimIDParameter = seqClaimID != null ?
                new ObjectParameter("SeqClaimID", seqClaimID) :
                new ObjectParameter("SeqClaimID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Get_ClaimHeader_Result>("sp_Get_ClaimHeader", clientMemberKeyParameter, seqClaimIDParameter);
        }
    
        public virtual ObjectResult<sp_Get_ClaimPharmacy_Result> sp_Get_ClaimPharmacy(string clientMemberKey, string seqClaimID)
        {
            var clientMemberKeyParameter = clientMemberKey != null ?
                new ObjectParameter("ClientMemberKey", clientMemberKey) :
                new ObjectParameter("ClientMemberKey", typeof(string));
    
            var seqClaimIDParameter = seqClaimID != null ?
                new ObjectParameter("SeqClaimID", seqClaimID) :
                new ObjectParameter("SeqClaimID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Get_ClaimPharmacy_Result>("sp_Get_ClaimPharmacy", clientMemberKeyParameter, seqClaimIDParameter);
        }
    }
}
